version: "3.8"

networks:
  my-bridge:
    external: true

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes --save 60 1000 --loglevel notice --requirepass ${REDIS_PASSWORD}
    networks:
      - my-bridge


  spring:
    container_name: spring
    image: ${DOCKERHUB_USERNAME}/sonic
    depends_on:
      - redis
    ports:
      - "8080:8080"
    logging:
        driver: "json-file",
        options:
          max-size: "1000m"
          max-file: "5"
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - jwt.secret=${jwt_secret}
      - kakao.client.id=${kakao_client_id}
      - aws.credentials.secret-key=${aws_credentials_secret_key}
      - aws.credentials.access-key=${aws_credentials_access_key}
      - aws.region.static=${aws_region_static}
      - cloud.aws.s3.bucket=${cloud_aws_s3_bucket}
      - redis.host=redis
      - redis.port=6379
      - redis.password=${REDIS_PASSWORD}
    restart: always
    networks:
      - my-bridge