version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --save 60 1000 --loglevel notice --requirepass ${REDIS_PASSWORD}


  spring:
    container_name: spring
    image: ${DOCKERHUB_USERNAME}/sonic
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"