version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  spring:
    container_name: spring
    image: ${DOCKERHUB_USERNAME}/sonic
    depends_on:
      - redis
    WAIT_HOSTS: redis:6379
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - jwt.secret=${jwt_secret}
      - kakao.client.id=${kakao_client_id}
      - aws.credentials.secret-key=${aws_credentials_secret_key}
      - aws.credentials.access-key=${aws_credentials_access_key}
      - aws.region.static=${aws_region_static}
      - cloud.aws.s3.bucket=${cloud_aws_s3_bucket}
    ports:
      - "8080:8080"
    restart: always