name: Java CI with Gradle

on:
  push:
    branches: [ "local-CICD" ]

jobs:
  build-docker-image:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up application.properties
      run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/security.properties

    - name: Run chmod to make graldew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew --warning-mode all clean build --exclude-task test

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sonic .
 
    - name: docker login
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_KEY}}
 
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/sonic
